RigidBody
	name fillerObj
	mass 3
	moi 1 1 1
	colour 0 0 1 1
	position 1 1 1
	
	CDP_Sphere 0 0 0 0.01
	
	frictionCoefficient 0.000008
	restitutionCoefficient 0.8	
	
	ODEGroundParameters 0.0005 0.5

/End